# Generated by Django 4.2.4 on 2023-08-16 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardealer',
            name='area',
        ),
        migrations.RemoveField(
            model_name='cardealer',
            name='car_dealer',
        ),
        migrations.RemoveField(
            model_name='vehicles',
            name='area',
        ),
        migrations.RemoveField(
            model_name='vehicles',
            name='dealer',
        ),
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.DeleteModel(
            name='CarDealer',
        ),
        migrations.DeleteModel(
            name='Vehicles',
        ),
    ]
